ARDUINO_DIR = /usr/share/arduino

TARGET       = Blink
MCU          = atmega328p
F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyACM0
#ARDUINO_LIBS =
AVRDUDE_ARD_BAUDRATE = 115200

include /usr/share/arduino/Arduino.mk

# To upload, run make upload
